Repository smileidentity/react-native-expo, pull requests merged in 2025-07, with the labels that each got.

#27 Feat: Add Smart Selfie Enrollment params functionality on Android & iOS
  android/src/main/java/com/smileidentity/react/expo/SmileIDExpoModule.kt
  android/src/main/java/com/smileidentity/react/expo/SmileIDExpoRecords.kt
  android/src/main/java/com/smileidentity/react/expo/SmileIDSmartSelfieEnrollmentView.kt
  example/HomeScreen.tsx
  ios/SmileIDExpoModule.swift
  ios/SmileIDExpoRecords.swift
  ios/SmileIDSmartSelfieEnrollmentView.swift
  src/products/SmileIDSmartSelfieEnrollmentView.tsx
  src/types/SmileIDExpo.types.ts
Labels: Review effort 3/5

#32 Feat: Support Other Initialization Options on iOS + Use Specific SmileSecurity Version
  example/ios/Podfile.lock
  ios/SmileIDDocumentVerificationView.swift
  ios/SmileIDExpo.podspec
  ios/SmileIDExpoModule.swift
Labels: Review effort 2/5

#36 Feat: Add Biometric KYC + Cleanup Consent + Enhanced KYC For Now
  android/src/main/java/com/smileidentity/react/expo/SmileIDBiometricKYCView.kt
  android/src/main/java/com/smileidentity/react/expo/SmileIDExpoModule.kt
  android/src/main/java/com/smileidentity/react/expo/SmileIDExpoRecords.kt
  ios/SmileIDBiometricKYCView.swift
  ios/SmileIDExpoModule.swift
  ios/SmileIDExpoRecords.swift
  sample-expo/HomeScreen.tsx
  src/index.ts
  src/products/SmileIDBiometricKYCView.tsx
  src/products/SmileIDBvnConsentScreenView.tsx
  src/products/SmileIDEnhancedKyCView.tsx
  src/types/SmileIDExpo.types.ts
Labels: Review effort 3/5

#42 update CONTRIBUTING
  CONTRIBUTING.md
Labels: Review effort 1/5

#43 Set Wrapper SDK Info
  android/src/main/java/com/smileidentity/react/expo/SmileIDExpoModule.kt
  ios/SmileIDExpoModule.swift
Labels: Review effort 2/5

#45 Fix Enhanced Selfie Capture on iOS
  ios/SmileIDSmartSelfieAuthenticationEnhancedView.swift
  ios/SmileIDSmartSelfieEnrollmentEnhancedView.swift
Labels: Review effort 2/5

#48 Fix react-native sample app
  ios/SmileIDSmartSelfieAuthenticationEnhancedView.swift
  sample-react-native/package-lock.json
  sample-react-native/package.json
  sample-react-native/yarn.lock
Labels: Review effort 2/5

#47 Feat: Expose More SDK Functions
  android/src/main/java/com/smileidentity/react/expo/SmileIDExpoModule.kt
  ios/SmileIDExpoModule.swift
  sample-expo/HomeScreen.tsx
  sample-react-native/HomeScreen.tsx
  src/SmileIDExpoModule.ts
  src/index.ts
  src/types/SmileIDExpo.types.ts
Labels: Review effort 3/5

#50 Upgrade Target Compile SDK 🦊
  android/build.gradle
  sample-react-native/android/build.gradle
  sample-react-native/yarn.lock
Labels: Review effort 2/5

#53 Prep: Initial Release
  CHANGELOG.md
  package.json
Labels: Review effort 1/5
